<div class="header">
            <nav class="navbar navbar-expand-lg py-0">
                <div class="container-fluid">
                <a class="navbar-brand me-4" href="index.php">
                    <img class="img-fluid" width="70" src="assets/images/SkillSwap_logo.png" alt="skill Swap logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse nav-item" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 text-md-center">
                <li class="nav-item">
                    <a class="nav-link ysabeau-sc-NavBar me-3" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ysabeau-sc-NavBar me-3" href="skills.php"> All Skills </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ysabeau-sc-NavBar me-3" href="gallery.php"> Gallery </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ysabeau-sc-NavBar me-3" href="add.php"> Add Skills </a>
                </li>
            </ul>
            <form class="ms-auto mb-2 mt-2 d-flex p-md-3" role="search">
                    <a class="nav-link ysabeau-sc-NavBar mt-1 me-3" href="login.php">Login </a>
                    <a class="nav-link ysabeau-sc-NavBar mt-1 me-3" href="register.php">Register </a>

                <div class="input-group">
                <button type="submit" class="btn search-btn text-gray material-symbols-outlined">
                        search
                </button>
                <input class="form-control bg-light ysabeau-sc-NavBar" type="search" placeholder="Search skills..." aria-label="Search">
                </div>
            </form>
            </div>
            </div>
        </nav>
        </div>
